### ISSUE TITLE
Failed to fetch user profile

### ISSUE THREAD

**Issue by chornthorn** [zgid123/passport-google-oauth-token#16]
What could be causing the "Failed to fetch user profile" error in the following code snippet?

`[Nest] 25314 - 06/23/2023, 7:18:03 PM ERROR [ExceptionsHandler] Failed to fetch user profile
InternalOAuthError: Failed to fetch user profile`

What steps would you take to troubleshoot this issue and resolve the error?
I use nestjs v10.0.0

**Comment by zgid123** [comment]
Lemme check it tomorrow

**Comment by chornthorn** [comment]
Oh! Sorry, dear, I'm wrong access token from mobile.

**Comment by chornthorn** [comment]
Can you close this issue

**Comment by chornthorn** [comment]
But can you help share with me to handle error 500 when the access token is invalid?

**Comment by zgid123** [comment]
For nestjs, you will use @nestjs/passport, so you need to create a [filter](https://docs.nestjs.com/exception-filters) to handle it

**Comment by zgid123** [comment]
Or you can create new auth decorator based on [this one](https://github.com/nestjs/passport/blob/master/lib/auth.guard.ts). I am using global filter to handle it

**Comment by chornthorn** [comment]
Thank you so much!

**Comment by zgid123** [comment]
I think this issue is solved. I will close it, if you have any problem, you can reopen this one or create new issue. I will take a look later
