### ISSUE TITLE
Adding support for "hd" or "hostedDomain" parameter

### ISSUE THREAD

**Issue by xAbdaziz** [zgid123/passport-google-oauth-token#17]
Hello, can this parameter be added?
it exists in the passport-google-oauth2 library

https://github.com/jaredhanson/passport-google-oauth2/blob/79f9ed6878f1d11150243a1429acb7ba3211e239/lib/strategy.js#L159

**Comment by zgid123** [comment]
hmm, I haven't applied this parameter, lemme have a test then

**Comment by xAbdaziz** [comment]
> hmm, I haven't applied this parameter, lemme have a test then

Nevermind
I'm sorry, I thought this library redirects to Google's Sign-in page like passport-google-oauth2 does
turns out it doesn't, so it is useless to add hd/hostedDomain parameter

Thanks anyway for the reply!
